<?php

arch('application code uses strict domain namespaces')
    ->expect('App\Modules')
    ->toOnlyUse([
        'App\Modules',
        'Illuminate',
        'Inertia',
        'Psr',
        'Carbon',
        'Symfony',
        'Symfony\Component\HttpFoundation\Response',
        'Closure',
        'DateTimeInterface',
        'DateTimeImmutable',
        'InvalidArgumentException',
        'abort',
        'abort_if',
        'abort_unless',
        'app',
        'back',
        'bindec',
        'chr',
        'config',
        'decbin',
        'event',
        'hash',
        'hash_equals',
        'hash_hmac',
        'intdiv',
        'intval',
        'is_array',
        'is_string',
        'now',
        'ord',
        'pack',
        'preg_match',
        'random_bytes',
        'rawurlencode',
        'redirect',
        'response',
        'route',
        'str_contains',
        'str_pad',
        'str_split',
        'strlen',
        'strpos',
        'time',
    ]);

arch('module infrastructure is not a model namespace')
    ->expect('App\Modules\Platform\Infrastructure')
    ->not->toHaveSuffix('Model');
