export const TARGET_COUNTRIES = [
    ['CI', "Côte d'Ivoire"],
    ['SN', 'Sénégal'],
    ['ML', 'Mali'],
    ['BF', 'Burkina Faso'],
    ['GN', 'Guinée'],
    ['GH', 'Ghana'],
    ['TG', 'Togo'],
    ['BJ', 'Bénin'],
    ['NE', 'Niger'],
    ['NG', 'Nigeria'],
    ['LR', 'Liberia'],
    ['SL', 'Sierra Leone'],
    ['GM', 'Gambie'],
    ['GW', 'Guinée-Bissau'],
    ['MR', 'Mauritanie'],
    ['CV', 'Cap-Vert'],
    ['CM', 'Cameroun'],
    ['GA', 'Gabon'],
    ['CG', 'Congo'],
    ['CD', 'RDC'],
    ['MA', 'Maroc'],
    ['DZ', 'Algérie'],
    ['TN', 'Tunisie'],
    ['FR', 'France'],
    ['CA', 'Canada'],
    ['US', 'États-Unis'],
] as const;
